# Fly.io configuration for Papers2Code Backend
# See full documentation at https://fly.io/docs/reference/configuration/

app = "papers2code-backend"
primary_region = "iad"  # Washington, D.C. - change to your preferred region

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  ENV_TYPE = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "GET"
    path = "/health"

[deploy]
  release_command = "uv sync"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
