services:
  - type: web
    env: python
    buildCommand: uv sync --frozen && uv cache prune --ci
    startCommand: uv run run.py
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11

